plugins {
    id 'com.android.application'
}

def keystorePropsFile = rootProject.file('keystore.properties')
def keystoreProps = new Properties()
if (keystorePropsFile.exists()) {
    keystoreProps.load(new FileInputStream(keystorePropsFile))
}

android {
    namespace 'com.zm920.androidserver'
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId 'com.zm920.androidserver'
        minSdk 24
        targetSdk 34
        versionCode 6
        versionName '1.6'
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt',
                         'META-INF/NOTICE', 'META-INF/NOTICE.txt']
            pickFirsts += ['META-INF/AL2.0', 'META-INF/LGPL2.1']
        }
    }

    signingConfigs {
        release {
            storeFile rootProject.file(keystoreProps.getProperty('storeFile', 'keys/zm.jks'))
            storePassword keystoreProps.getProperty('storePassword', '')
            keyAlias keystoreProps.getProperty('keyAlias', '')
            keyPassword keystoreProps.getProperty('keyPassword', '')
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.navigation:navigation-fragment:2.7.7'
    implementation 'androidx.navigation:navigation-ui:2.7.7'
    // 友盟统计
    implementation 'com.umeng.umsdk:common:9.6.2'
    implementation 'com.umeng.umsdk:asms:1.8.0'

    implementation 'org.apache.ftpserver:ftpserver-core:1.2.0'
    implementation 'org.java-websocket:Java-WebSocket:1.5.6'
    implementation 'org.apache.mina:mina-core:2.1.6'
    implementation 'org.slf4j:slf4j-android:1.7.36'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
